# Generated by Django 5.1.1 on 2024-09-15 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("complete", models.BooleanField(db_index=True, default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "To-Do",
                "verbose_name_plural": "To-Dos",
                "ordering": ["-updated"],
                "indexes": [
                    models.Index(
                        fields=["user", "complete"], name="todo_todo_user_id_98bbbd_idx"
                    )
                ],
            },
        ),
    ]
