# Generated by Django 5.1.1 on 2024-09-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_todo_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["-created_at"]},
        ),
    ]
