from rest_framework import permissions
from rest_framework.decorators import action
# import responce
from djoser.views import UserViewSet as DjoserUserViewSet
from drf_spectacular.utils import extend_schema
from users.serializers import CustomUserCreateSerializer,CustomUserUpdateSerializer
from users.models import CustomUser
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

class CustomUserViewSet(DjoserUserViewSet):
    queryset=CustomUser.objects.all()
    serializer_class = CustomUserCreateSerializer

    # me endpoints
    @extend_schema(
        tags=["me"],
        summary="GET the current authenticated user's profile",
        description="Endpoint to GET current authenticated user's profile",
        methods=["GET"],
    )
    @extend_schema(
        tags=["me"],
        summary="Update the current authenticated user's profile",
        description="Endpoint to Update current authenticated user's profile (full_name and email required).",
        request=CustomUserUpdateSerializer,
        methods=["PUT", "PATCH"],
    )
    @action(
        methods=['get', 'put', 'patch'],
        detail=False,
        permission_classes=[permissions.IsAuthenticated],
    )
    def me(self, request, *args, **kwargs):
        # Call the inherited me() method from DjoserUserViewSet
        return super().me(request, *args, **kwargs)


# Auth Operations endpoints

    # Override other Djoser endpoints and tag them under 'auth'
    @extend_schema(
        tags=["auth"],
        summary="List Registered Users",
        description="Endpoint to List registered users."
        )
    def list(self, request, *args, **kwargs):
        # List users (admin access)
        return super().list(request, *args, **kwargs)
    
    @extend_schema(
        tags=["auth"],
        summary="Create new user",
        description="Endpoint to create new user"
        )
    def create(self, request, *args, **kwargs):
        # Create a new user
        return super().create(request, *args, **kwargs)
    
    @extend_schema(tags=["auth"],summary="Get User Profile",description="Endpoint to get user profile.")
    def retrieve(self, request, *args, **kwargs):
        # Retrieve user profile by uuid
        return super().retrieve(request, *args, **kwargs)

    @extend_schema(
        tags=["auth"],
        summary="Update users profile",
        description="Endpoint to Update user profile full_name. NOTE: You need to provide email as well for this endpoint to work.",
        request=CustomUserUpdateSerializer,
        )
    def update(self, request, *args, **kwargs):
        self.serializer_class=CustomUserUpdateSerializer
        return super().update(request,*args,**kwargs)
    
    @extend_schema(
        tags=["auth"],
        summary="Endpoint to update user profile",
        description="Endpoint to Update user profile full_name.",
        request=CustomUserUpdateSerializer,
        )
    def partial_update(self, request, *args, **kwargs):
        # Partial update user profile (PATCH)
        self.serializer_class=CustomUserUpdateSerializer
        return super().partial_update(request,*args,**kwargs)

    @extend_schema(
        tags=["auth"],
        summary="Activate user account using `uid` and `token`",
        description="Endpoint to Activate User account using `uid` and `token` generated on register or using `/resend_activation/` resource.",
    )
    def activation(self, request, *args, **kwargs):
        return super().activation(request, *args, **kwargs)
    
    @extend_schema(
        tags=["auth"],
        summary="Generate and send activation `uid` and `token` for User account.",
        description="Endpoint to Generate and send activation `uid` and `token` for User account.",
    )
    def resend_activation(self, request, *args, **kwargs):
        return super().resend_activation(request, *args, **kwargs)

    @extend_schema(
        tags=["auth"],
        summary="send password reset email",
        description="Endpoint to Send password reset email using current user email",
    )
    def reset_password(self, request, *args, **kwargs):
        return super().reset_password(request, *args, **kwargs)

    @extend_schema(
        tags=["auth"],
        summary="Reset password using `uid` and `token`",
        description="Endpoint to Reset password using `uid` and `token` generated by `/reset_password/` resource for current authenticated user."
        )
    def reset_password_confirm(self, request, *args, **kwargs):
        return super().reset_password_confirm(request, *args, **kwargs)

    @extend_schema(
        tags=["auth"],
        summary="Change user password.",
        description="Endpoint to Change user password using current password.",
    )
    def change_password(self, request, *args, **kwargs):
        return super().change_password(request, *args, **kwargs)

    

# JWT api endpoints
@extend_schema(
    summary="Generate access and refresh tokens",
    description="Takes a set of user credentials and returns an access and refresh JSON web token pair.",
    tags=["jwt"],
)
class CustomTokenObtainPairView(TokenObtainPairView):
    pass

@extend_schema(
    summary="Refresh access token",
    description="Takes a valid refresh token and returns a new access token.",
    tags=["jwt"],
)
class CustomTokenRefreshView(TokenRefreshView):
    pass

@extend_schema(
    summary="Verify access token validity",
    description="Verifies if a given token is valid.",
    tags=["jwt"],
)
class CustomTokenVerifyView(TokenVerifyView):
    pass
